#runtime: php
#env: flex
#
#runtime_config:
#  document_root: .
#
#automatic_scaling:
#    min_num_instances: 1
#    max_num_instances: 8
#    cool_down_period_sec: 180
#    cpu_utilization:
#      target_utilization: 0.6
#    target_concurrent_requests: 100

runtime: php74 # Replace with php74 to use PHP 7.4
